name: CI

on:
  pull_request:
  push:
    branches: [task_ci] # TODO: dev

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  PHP_VERSION: "8.3"
  BUN_VERSION: "1.3.2"
jobs:
  ci:
    uses: WandryDev/laravel-react-workflow/.github/workflows/ci.yml@v1
    with:
      backend_lint: false
      backend_test: false
